version: "3"

services:
  # 서비스 명
  postgresql:
    # 사용할 이미지
    image: postgres:15.2
    # 컨테이너 실행 시 재시작
    restart: always
    # 컨테이너명 설정
    container_name: postgres
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "5432:5432"
    # 환경 변수 설정
    environment:
      # PostgreSQL 계정 및 패스워드 설정 옵션, 데이터베이스 설정
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: test
    # 볼륨 설정
    volumes:
      - ~/data/postgres/:/var/lib/postgresql/data
