name: development CI

on:
  push:
    branches-ignore:
      - "release"
  pull_request:
    branches-ignore:
      - "release"

jobs:
  nest_CI:
    runs-on: ubuntu-latest
    env:
      working-directory: ./hello-typeorm

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Check current Dir
        run: pwd
        working-directory: ./hello-typeorm

      - name: Check dir
        run: ls -al
        working-directory: ./hello-typeorm

      - name: Install dependencies
        run: yarn install
        working-directory: ./hello-typeorm

      - name: Test unit
        run: yarn test:unit
        working-directory: ./hello-typeorm
